### ISSUE TITLE
Extend behavior of interp1d_unc at boundaries to mimic numpy.interp

### ISSUE THREAD

**Issue by eichstaedtPTB** [PTB-PSt1/PyDynamic#110]
In numpy interp there are keyword arguments `left`and `right`:
```python
left : optional float or complex corresponding to fp
Value to return for x < xp[0], default is fp[0].

right : optional float or complex corresponding to fp
Value to return for x > xp[-1], default is fp[-1].
```
I'd suggest that this behavior should be mimicked in `uncertainty.interp1_unc`. Uncertainties could be "extrapolated" in the same way as the value itself (although more sophisticated model-based extrapolation could be preferred in a future release).

**Comment by BjoernLudwigPTB** [comment]
> In numpy interp there are keyword arguments `left`and `right`:
> 
> ```python
> left : optional float or complex corresponding to fp
> Value to return for x < xp[0], default is fp[0].
> 
> right : optional float or complex corresponding to fp
> Value to return for x > xp[-1], default is fp[-1].
> ```
> 
> I'd suggest that this behavior should be mimicked in `uncertainty.interp1_unc`. Uncertainties could be "extrapolated" in the same way as the value itself (although more sophisticated model-based extrapolation could be preferred in a future release).

I was reluctant to implement this in the first versions because of the decisions that would be involved regarding which way to go. Since we could actually quickly extend the current implementation with this feature, we might as well do it soon. Your suggestion would be one approach. Another would be the [scipy.interpolate.interp1d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html#scipy-interpolate-interp1d) way, which has a slightly different signature for this (parameters `bounds_error` and `fill_value`), which I would prefer over the numpy version, since we want to stick to the scipy signature for the currently implemented feature as we just discuss in #109.

@eichstaedtPTB  What do you think?

**Comment by eichstaedtPTB** [comment]
I agree to stick with the scipy signature. The behavior of the method itself seems to be quite similar to that of numpy when using the fill_value parameter correspondingly.
```
If a two-element tuple, then the first element is used as a fill value for x_new < x[0] and the second
element is used for x_new > x[-1]. Anything that is not a 2-element tuple (e.g., list or ndarray, 
regardless of shape) is taken to be a single array-like argument meant to be used for both bounds
as below, above = fill_value, fill_value.

´´´

**Comment by BjoernLudwigPTB** [comment]
@eichstaedtPTB since you already have a snippet which does that, could you copy-paste it here without much effort?
